image: docker:git

variables:
  RASPBIAN_VERSION: '2019-04-08'
  DOCKER_REPOSITORY: 'mendersoftware/mender-test-containers'
  DOCKER_HUB_USERNAME: 'menderbuildsystem'

stages:
  - test
  - build_prep
  - build
  - publish

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits-signoffs.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-python3-format.yml'

build_prep:
  stage: build_prep
  image: buildpack-deps:scm
  script:
    - cd docker/docker-files-raspbian
    - apt-get update && apt-get install -yyq sudo unzip
    - ./prepare-raspbian-img.sh ${RASPBIAN_VERSION}
    - cd .. && tar -cvf $CI_PROJECT_DIR/docker-files-raspbian.tar docker-files-raspbian
  artifacts:
    expire_in: 2w
    paths:
      - docker-files-raspbian.tar
  tags:
    - mender-qa-slave

build:
  stage: build
  dependencies:
    - build_prep
  services:
    - docker:dind
  script:
    - tar -xvf docker-files-raspbian.tar
    - docker build --build-arg raspbian_version=${RASPBIAN_VERSION} -t $DOCKER_REPOSITORY:pr docker-files-raspbian
    - docker save $DOCKER_REPOSITORY:pr > image.tar
  artifacts:
    expire_in: 2w
    paths:
      - image.tar

build:testing:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_REPOSITORY:acceptance-testing -f backend-acceptance-testing/Dockerfile.backend-tests backend-acceptance-testing
    - docker save $DOCKER_REPOSITORY:acceptance-testing > testingImage.tar
  artifacts:
    expire_in: 2w
    paths:
      - testingImage.tar

build:qa:
  stage: build
  tags:
    - mender-qa-slave-highcpu
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_REPOSITORY:mender-client-acceptance-testing -f mender-client-acceptance-testing/Dockerfile mender-client-acceptance-testing
    - docker save $DOCKER_REPOSITORY:mender-client-acceptance-testing > qaTestingImage.tar
  artifacts:
    expire_in: 2w
    paths:
      - qaTestingImage.tar

build:downstream:
  stage: build
  trigger: Northern.tech/Mender/deviceauth

publish:build:master:
  stage: publish
  dependencies:
    - build
    - build:testing
    - build:qa
  services:
    - docker:dind
  script:
    - echo "publishing image to Docker hub"
    - docker load -i image.tar
    - export COMMIT_TAG="$CI_COMMIT_REF_NAME"_"$CI_COMMIT_SHA";
    - docker tag $DOCKER_REPOSITORY:pr $DOCKER_REPOSITORY:$COMMIT_TAG;
    - docker rmi $DOCKER_REPOSITORY:pr
    - docker tag $DOCKER_REPOSITORY:$COMMIT_TAG $DOCKER_REPOSITORY:raspbian_latest;
    - echo -n $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker push $DOCKER_REPOSITORY:raspbian_latest;
    - docker load -i testingImage.tar
    - docker push $DOCKER_REPOSITORY:acceptance-testing
    - docker load -i qaTestingImage.tar
    - docker push $DOCKER_REPOSITORY:mender-client-acceptance-testing
  only:
    - master
  tags:
    - docker
